name: peterheidorn
favicon: null
layout_spectrum: 0.932432
typography_spectrum: 0.844594
title: Black Bear Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D0B8'
    - '#5C4929'
    - '#C0A878'
    - '#B89860'
    - '#F8F0E0'
  brandStrength: 0.173986
  lightness: 0.177514
  saturation: 0.637663
  rhythmicContrast: 0.819467
purpose: []
