name: Black Bear Marketing
favicon: null
layout_spectrum: 0.932432
typography_spectrum: 0.844594
title: Black Bear Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67abfe'
    - '#a20000'
    - '#1f1027'
    - '#ffffff'
    - '#efb85e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
