analytics: {}
color:
  brandColors:
    - '#D8D0B8'
    - '#5C4929'
    - '#C0A878'
    - '#B89860'
    - '#F8F0E0'
  brandStrength: 0.173986
  lightness: 0.177514
  rhythmicContrast: 0.819467
  saturation: 0.637663
cta: {}
layout_spectrum: 0.932432
name: peterheidorn
opengraph: {}
purpose: []
typography_spectrum: 0.844594
